name: report-test-results

on:
  workflow_run:
    workflows: [ 'run-tests' ]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Print info about the target workflow_run
        run : |
          echo "workflow_run: ${{ github.event.workflow_run }}"
          echo "head_sha: ${{ github.event.workflow_run.head_sha }}"
          echo "workflow_id: ${{ github.event.workflow_run.workflow_id }}"
          echo "head_branch: ${{ github.event.workflow_run.head_branch }}"
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
      - name: Display structure of downloaded files
        run: ls -R
      - name: Report tests results
        uses: AndreyAkinshin/test-reporter@0e2c48ebec2007001dd77dd4bcbcd450b96d5a38
        with:
          name: report
          path: "**/*.trx"
          reporter: dotnet-trx
          fail-on-error: true