name: report-test-results

on:
  workflow_run:
    workflows: [ 'test' ]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: Report tests results
        uses: AndreyAkinshin/test-reporter@0e2c48ebec2007001dd77dd4bcbcd450b96d5a38
        if: always()
        with:
          name: test-results
          path: "**/*.trx"
          reporter: dotnet-trx
          fail-on-error: true